apiVersion: v1
kind: Service
metadata:
  name: senderservice-service
  namespace: sender
spec:
  type: NodePort
  selector:
    app: senderservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # You can choose any port between 30000-32767
